# This is the AIPACK lab@loop AI Pack for loop coding
[pack]
namespace = "lab"  # aipack.ai lab namespace
name      = "loop" # pack name (so aip install lab@ako)
version   = "0.1.0"

license  = "MIT or Apache 2"
homepage = "https://aipack.ai/"
repo     = "https://github.com/aipack-ai/aipack-lab"
author   = "Jeremy Chone"
email    = "jeremy.chone@gmail.com"



